version: '3.7'
services:
  corn-app:
    build:
      context: ../
      dockerfile: .docker/configs/debian/Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ../:/var/www/project:delegated
